### ISSUE TITLE
All Quicktexts Are Gone :(

### ISSUE THREAD

**Issue by sprankhub** [gorgias/gorgias-chrome#103]
Today I noticed that all my quicktexts in Chromium 40.0.2214.111 Ubuntu 14.04 (64-bit) are gone :( Probably after the automatic upgrade to 2.5.0. Any chance to restore the texts?

**Comment by xarg** [comment]
Simon, do you have the new update 2.5.2? They should have been restored.

Alex.

**Comment by sprankhub** [comment]
Great, thank you so much!

**Comment by sprankhub** [comment]
With the latest version 2.5.4, the texts are gone again :/

**Comment by xarg** [comment]
Sorry again! Can you go to extensions and click on 'Inspect views: pages/bg.html' see if you have any errors.

**Comment by sprankhub** [comment]
TypeError: Cannot set property 'enabled' of undefined
        at chrome-extension://lmcngpkjkplipamgflhioabnhnopeabf/background/js/background.js:60597:45
        at processQueue (chrome-extension://lmcngpkjkplipamgflhioabnhnopeabf/background/js/background.js:33749:27)
        at chrome-extension://lmcngpkjkplipamgflhioabnhnopeabf/background/js/background.js:33765:27
        at Scope.$eval (chrome-extension://lmcngpkjkplipamgflhioabnhnopeabf/background/js/background.js:34961:28)
        at Scope.$digest (chrome-extension://lmcngpkjkplipamgflhioabnhnopeabf/background/js/background.js:34777:31)
        at chrome-extension://lmcngpkjkplipamgflhioabnhnopeabf/background/js/background.js:35000:26
        at completeOutstandingRequest (chrome-extension://lmcngpkjkplipamgflhioabnhnopeabf/background/js/background.js:25465:10)
        at chrome-extension://lmcngpkjkplipamgflhioabnhnopeabf/background/js/background.js:25845:7 undefinedbackground.js:32167 (anonymous function)
    https://app.getsentry.com/api/30379/store/?sentry_version=4&sentry_client=r…222.5.4%22%7D%2C%22event_id%22%3A%2249deb4e2434d4e03aac74ab48ee78764%22%7D Failed to load resource: the server responded with a status of 414 (Request-URI Too Large)

**Comment by xarg** [comment]
Darn! I know why.. you have an update soon!

**Comment by xarg** [comment]
I just released a new version (2.5.5). Should be distributed in an hour or so.

**Comment by sprankhub** [comment]
Thanks!
